### ISSUE TITLE
Tracker dragon, bad result with new dataset

### ISSUE THREAD

**Issue by ColletAxel** [lvsn/6DOF_tracking_evaluation#2]
Hello,
I've train your tracker with your program [provide](https://github.com/lvsn/deeptracking) with the dragon model. When I test your tracker with the sequence provide by this [program](https://github.com/lvsn/deeptrack_dataset) I' have really good result. But when i'm trying with the new [dataset](http://vision.gel.ulaval.ca/~jflalonde/projects/6dofObjectTracking/index.html) the result are less good for the rotation.

**Old dataset dragon sequence :**
![c](https://user-images.githubusercontent.com/29093782/48076349-4cf9cd80-e1e5-11e8-82bb-877dff938b42.png)

**New dataset sequence with occlusion_0 sequence :**
![d](https://user-images.githubusercontent.com/29093782/48076328-4408fc00-e1e5-11e8-9da4-34e489c57e21.png)

Did you know how can I have better result with the new dataset ? 

If I need to train again the neural network with the model of the second dataset. I have few more questions : 

- The model doesn't include the ambiant occlusion file (ao.ply) are they essential ? If yes how can I generate them ?
- How the object_width parameter from the configuration file are determined ?

Thanks in advance 
Axel Collet
Student at hepia

Parameter of the model : 
```

 "models": [

    {
      "name": "model_dragon",
      "model_path": "/home/collet/6dof_Laval/deeptrack_dataset/data/3dmodels/dragon/geometry.ply",
      "ambiant_occlusion_model": "/home/collet/6dof_Laval/deeptrack_dataset/data/3dmodels/dragon/ao.ply",
      "object_width": "200"
    }
    ],

```

**Comment by MathGaron** [comment]
Hey Axel,

Indeed there is obviously a bug with the rotation (rotations always give me headaches!). I have a few guesses that might help you to debug it:
- First, the two dragon models are actually different, we did a second scan for the [ECCV18 dataset](http://vision.gel.ulaval.ca/~jflalonde/projects/6dofObjectTracking/index.html). So the first thing to check is the origin of their coordinate system, they might be quite different. If you use for example dragon 1 as a ground truth for dataset 2, the ground truth may be wrong.
Note that deeptrack should still be able to track the object as it don't really care about the coordinate system unless the initial position is way off. (If you check the sequence, does the tracking still look good even if the results are bad?)
- Second, the ground truths are processed differently on both dataset. If you look in the new [transform utility](https://github.com/lvsn/6DOF_tracking_evaluation/blob/master/ulaval_6dof_object_tracking/utils/transform.py) line 23 and 101, I use Rodrigues to compute the rotations instead of Euler ZYX in the [previous utility](https://github.com/lvsn/deeptracking/blob/master/deeptracking/utils/transform.py). So if you convert the rotation matrix from dataset 2 to euler ZYX, it might not be what you expect. Make sure you are consistent in the rotation conventions.

So retraining is not necessary, you could simply make sure that the initial position (rotation) is fine, and make sure that the rotation matrix convention are used.

For your other questions : 
- ao.ply : The ambiant occlusion values are baked in the new models (vertex color), no need to load them explicitly.
- object_width : These were calculated with another script. At that time I would compute the distance between the farthest vertices on the object and add 10%-15%. We found out that simply using this distance gives the best results on average.

That said, the new models are much cleaner as we did a 360 scan of the object. The previous one have huge holes. It does not affect deeptrack heavily, but you might still be able to gain more performances.

Hope this helps! If you have any other question just ask.
Best

**Comment by ColletAxel** [comment]
Hello, 
I could correct the problem, it was well the computation of the rotation. 
Thanks for your answer Axel
