### ISSUE TITLE
Slow training

### ISSUE THREAD

**Issue by jpsml** [lvsn/6DOF_tracking_evaluation#6]
Hi, I am trying to train your tracker using a GTX 1060, but it is taking more than 30 minutes to complete only 25% of the first epoch. I have checked on nvidia-smi that the GPU is in fact being utilized. Do you know if this is expected or there is something wrong with my setup? Here you can find the output of my training procedure:

Start training
Load datasets from /media/jpsml/fa0ed448-9413-4678-ae56-e3d7f20395f5/deeptracking/test/
Save meta data in /media/jpsml/fa0ed448-9413-4678-ae56-e3d7f20395f5/deeptracking/to_delete/
Training Begins:
--------------------
 * EPOCH : 0
  0%|                                                                                                                                                                            | 0/16666 [00:00<?, ?it/s]/home/jpsml/.local/lib/python3.6/site-packages/torch/nn/functional.py:1320: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
 25%|████████████████████████████████████████▍                                                                                                                      | 4235/16666 [36:27<2:23:16,  1.45it/s]

**Comment by MathGaron** [comment]
First it depends on the size of the dataset, (on my setup it takes 16 min for a full epoch of 200 000 samples.)

I see that you have a huge number of batch to process (16666) what is the batch size? If you have space on your GPU you can make it between 64/132. I never tested with a higher minibatch size so it would be at your own risk!

Finally, the network is quite small, the main bottleneck of the training is actually CPU because of the heavy online data augmentation. (My setup has 20 cores.. and the GPU is still waiting for food ~30-50% of the time...) So it helps to be the only one using the CPUs, and launch as many process as available cores (look in the options, but the default will launch n_core processes. 
Potentially some data augmentation operation can be optimised (Watch out if you want to use the GPU though because it is multiprocess loading and can mess with Cuda context).

Else sadly you will have to be patient or get a new machine :( 

Hope it helps!
