### ISSUE TITLE
About inference stage of this work

### ISSUE THREAD

**Issue by Guptajakala** [lvsn/6DOF_tracking_evaluation#7]
Hi, thanks for sharing the code! Would you be able to release the code for inference stage of the network? I'm not quite clear either from the code or in the paper about how you do the inference. 
Did you apply any detection (e.g. YOLO, faster-RCNN) to get the bounding box of the interested object from the whole observed image and feed to the network? 

My another question is in the paper, it says "an image of the object at the predicted position (from the previous timestamp in the video sequence) x_pred". I wonder if as the tracking goes on, what if the drifted error accumulates and eventually make this bounding box no where close to the real object? What would happen then?

**Comment by MathGaron** [comment]
Hi,
I will probably release the code but can't give any date, as I am quite busy with other projects. But here is the answers to your question if you want to write it : 

As this is a tracking method, you need to initialise it with a detection method, so you need more than just a bounding box, you need the full 3D pose (3 translation, 3 rotations) of the object (you can have a certain error in accuracy as the tracker is robust to bad initialisation). 
From there the network will compute the new 6DOF pose for the new frame. Once you update the pose with the prediction, you can now render the object at this predicted pose, and crop both image based on the center of the object (that you project to 2D)
Actually I got an implementation in my previous version of the project, you can check [there](https://github.com/lvsn/deeptracking).

The initialisation is out of scope of this project, you might need something like SSD-6D, BB8 etc.

For the accumulating error, I refer you to this [paper](https://arxiv.org/pdf/1703.09771.pdf). The tracker can't drift because the error is fed back in the network using a *render*. A way to see it is in a static object case, if the network overshoot the prediction by 1 cm, the next render will be 1 cm off, it may then predict -1cm and go back to the right pose.

If you have any question, do not hesitate!

**Comment by Guptajakala** [comment]
Very helpful answer! thanks a lot!

**Comment by Guptajakala** [comment]
I checked your links, and there is one thing I still cannot understand:
From the beginning after initialized, you have the pose0 of frame0 and then the sensor get you frame1. Now according to the paper, you first render the object using the pose0 to render an object and use it as one input x_pred. Here why don't you directly crop the real image using the known pose0 instead of rendering? 
Another thing is that when you have frame1, how to get the interested object region as said in the paper "and an image of the observed object at the current timestamp x_obs" ?

**Comment by MathGaron** [comment]
The tracker has to be initialised by some pose. In the test it is actually the first frame. From there the tracker run on its own (until it loses track). If you simply crop the image for the first image, you will end up accumulating error. The reason is that the network is actually comparing the two images and finds the delta pose between both, however if you give the first image only by cropping the previous image and the pose is not what you expect, the network will compute a pose that does not add to your belief of the previous pose. By using a render, you actually *encode* the belief of the pose in the image and that way, the network can truly find the difference of pose between the render and the current image, and you can accumulate it to your previous pose.
Sorry I am trying my best to make it clear, but indeed it is not intuitive! I actually started this project thinking that feeding the cropped image would be the best solution!

So as I said previously, the crop is simply taking the center of the 3D model (center of mass) projecting this to the screen coord. From there, I project the boundary of the crop (w.r.t. the size of the object) and get the window in screen space. This way, the first frame always has its object perfectly centered in the crop with some orientation. Then you can just use the exact same window to crop the new frame. This way the network "clearly" see if there is a translation between the two images. (You can visualize the demo/generated data to see it).

Hope it helps!

**Comment by Guptajakala** [comment]
Sorry that I did not ask my question clearly, let me clarify it this way:

1) When you have the previous image and its pose, what you did is render the CAD model using that pose and use the synthetic image as one input. Did you try to use the CAD model to compute the bounding box and use that region inside the previous image as the input? Then the network will compare it with the current real image and predict the delta pose. Isn't this way also encoding the pose information, and at the same time the network is comparing two real images instead of one rendered synthetic image and the current real image?

2) In the synthetic data generator,  you are using the GT pose of the current frame (B), instead of pose of frame A, and extract the bounding box part as the code [here](https://github.com/Guptajakala/6DOF_tracking/blob/4ae6a9ee5762604af87cced8da907db2b329224e/ulaval_6dof_object_tracking/deeptrack/dataset_generator.py#L142). So during training, in both frame A and frame B, the object is ensured to be centered as they are using correct pose A and B. During test, are you using the previous frame's pose (A) to crop the current image (B) ? 

Thank you very much for your patience and I'd like to say this project is really awesome!

**Comment by MathGaron** [comment]
Thanks!
1. Providing the sensor image as the first will not work as explained earlier, the bounding box alone is not enough to encode the belief in the pose. Also don't forget that in our case we are following in 6DOF. Degrees like rotations are not encoded simply with a bounding box. Another thing is that doing a render make the job easier in a way where it "normalize" the input data received. Because the first frame always receives a centered object, the network don't have to be able to handle cases where the objects are off center in both images.

2. The previous pose A is always used to crop B, in the dataset generation and test time.

**Comment by Guptajakala** [comment]
Thanks a lot!
